name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [ dev, test, prod ]

    env:
      REGISTRY: 4erk
      IMAGE_NAME: swoole-docker


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'


      - name: Build Docker image
        run: |
          docker build --build-arg ENV=${{ matrix.environment }} --build-arg DEBUG=${{ matrix.environment == 'dev' }} -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.environment }} .


      - name: Extract version from composer.json
        id: extract_version
        run: |
          VERSION=$(php -r 'echo json_decode(file_get_contents("composer.json"), true)["version"];')
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image with version
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.environment }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.environment }}-${{ steps.extract_version.outputs.VERSION }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.environment }}-${{ steps.extract_version.outputs.VERSION }}

      - name: Push Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.environment }}