name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [ dev, test, prod ]

    env:
      REGISTRY: 4erk
      IMAGE_NAME: swoole-docker


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Extract version from composer.json
        id: extract_version
        run: |
          VERSION=$(php -r 'echo json_decode(file_get_contents("composer.json"), true)["version"];')
          echo "VERSION=${VERSION}" >> $GITHUB_STATE

      - name: Build Docker image
        run: |
          docker build --build-arg ENV=${{ matrix.environment }} --build-arg DEBUG=${{ matrix.environment == 'dev' }} -t $REGISTRY/$IMAGE_NAME:${{ matrix.environment }} .

      - name: Tag Docker image with version
        env:
          VERSION: ${{ steps.extract_version.outputs.VERSION }}
        run: |
          docker tag $REGISTRY/$IMAGE_NAME:${{ matrix.environment }} $REGISTRY/$IMAGE_NAME:${{ matrix.environment }}-${{ env.VERSION }}
          docker push $REGISTRY/$IMAGE_NAME:${{ matrix.environment }}-${{ VERSION }}

      - name: Push Docker image
        run: docker push $REGISTRY/$IMAGE_NAME:${{ matrix.environment }}

  publish:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from composer.json
        id: extract_version
        run: |
          VERSION=$(php -r 'echo json_decode(file_get_contents("composer.json"), true)["version"];')
          echo "VERSION=${VERSION}" >> $GITHUB_STATE

      - name: Pull built images
        env:
          VERSION: ${{ steps.extract_version.outputs.VERSION }}
        run: |
          docker pull $REGISTRY/$IMAGE_NAME:dev
          docker pull $REGISTRY/$IMAGE_NAME:test
          docker pull $REGISTRY/$IMAGE_NAME:prod
          docker pull $REGISTRY/$IMAGE_NAME:dev-${{ env.VERSION }}
          docker pull $REGISTRY/$IMAGE_NAME:test-${{ env.VERSION }}
          docker pull $REGISTRY/$IMAGE_NAME:prod-${{ env.VERSION }}

      - name: Push dev image
        env:
          VERSION: ${{ steps.extract_version.outputs.VERSION }}
        run: |
          docker push $REGISTRY/$IMAGE_NAME:dev
          docker push $REGISTRY/$IMAGE_NAME:dev-${{ env.VERSION }}

      - name: Push test image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:test
          docker push $REGISTRY/$IMAGE_NAME:test-${{ env.VERSION }}

      - name: Push prod image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:prod
          docker push $REGISTRY/$IMAGE_NAME:prod-${{ env.VERSION }}

      - name: Tag and push latest prod image
        if: matrix.environment == 'prod'
        run: |
          docker tag $REGISTRY/$IMAGE_NAME:prod-${{ env.VERSION }} $REGISTRY/$IMAGE_NAME:latest
          docker push $REGISTRY/$IMAGE_NAME:latest
