name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [ dev, test, prod ]

    env:
      REGISTRY: 4erk
      IMAGE_NAME: swoole-docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: swoole

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Update version
        run: php version-update.php

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Make changes
        run: |
          # Ваши команды для изменения файлов
          git add .
          git commit -m "chore(release): update version"

      - name: Push changes
        run: |
          git remote set-url origin "https://github.com/4erk/swoole-docker.git"
          git push origin main

      - name: Build Docker image
        run: |
          docker build --build-arg ENV=${{ matrix.environment }} --build-arg DEBUG=${{ matrix.environment == 'dev' }} -t $REGISTRY/$IMAGE_NAME:${{ matrix.environment }} .

      - name: Tag Docker image with version
        run: |
          docker tag $REGISTRY/$IMAGE_NAME:${{ matrix.environment }} $REGISTRY/$IMAGE_NAME:${{ matrix.environment }}-${{ env.VERSION }}
          docker push $REGISTRY/$IMAGE_NAME:${{ matrix.environment }}-${{ env.VERSION }}

      - name: Push Docker image
        run: docker push $REGISTRY/$IMAGE_NAME:${{ matrix.environment }}

  publish:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull built images
        run: |
          docker pull $REGISTRY/$IMAGE_NAME:dev
          docker pull $REGISTRY/$IMAGE_NAME:test
          docker pull $REGISTRY/$IMAGE_NAME:prod
          docker pull $REGISTRY/$IMAGE_NAME:dev-${{ env.VERSION }}
          docker pull $REGISTRY/$IMAGE_NAME:test-${{ env.VERSION }}
          docker pull $REGISTRY/$IMAGE_NAME:prod-${{ env.VERSION }}

      - name: Push dev image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:dev
          docker push $REGISTRY/$IMAGE_NAME:dev-${{ env.VERSION }}

      - name: Push test image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:test
          docker push $REGISTRY/$IMAGE_NAME:test-${{ env.VERSION }}

      - name: Push prod image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:prod
          docker push $REGISTRY/$IMAGE_NAME:prod-${{ env.VERSION }}

      - name: Tag and push latest prod image
        if: matrix.environment == 'prod'
        run: |
          docker tag $REGISTRY/$IMAGE_NAME:prod-${{ env.VERSION }} $REGISTRY/$IMAGE_NAME:latest
          docker push $REGISTRY/$IMAGE_NAME:latest
